apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-and-morty-api.fullname" . }}
  labels:
    {{- include "rick-and-morty-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "rick-and-morty-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
