name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: check pwd
      run: pwd 
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/charactersapi .
    - name: Push to Dockerhub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/charactersapi:latest

    - name: Run tests
      run: |
        python3 pytest
